### ISSUE TITLE
I'm Getting Undefined offset: 0

### ISSUE THREAD

**Issue by takielias** [samyan/omnipay-skrill#1]
Thanks for your valuable effort. But I'm getting this 

> Undefined offset: 0

How Can I fix it?

**Comment by samyan** [comment]
> Thanks for your valuable effort. But I'm getting this
> 
> > Undefined offset: 0
> 
> How Can I fix it?

Hello. Give more information please. Paste your code.

**Comment by takielias** [comment]
I got it. It's Merchant account issue. Is there any way to get a merchant account of skrill easily?

**Comment by samyan** [comment]
> I got it. It's Merchant account issue. Is there any way to get a merchant account of skrill easily?

Try to contact with **newbusiness@paysafe.com**
